### PR TITLE
production: remove all matching chunks correctly

### LINKED ISSUE #21: I18n compiled data ends up in app chunk instead of i18n chunk
Impact

On production, I18n compiled data ends up in app chunk instead of i18n chunk. Therefore: (a) chunks are incorrectly ordered: vendor, app, i18n, which leads to unavailable formatters, and (b) the English version (or whatever the default locale is) gets leaked in the app as a garbage.

How to reproduce: I'm not sure, on a project I'm working on I've observed this issue. See description below.

Description:

For some unknown reason, certain modules (in webpack terms) don't show up in any chunks (in webpack terms) on `after-optimize-chunks`. Interestingly, the same module shows up in a chunk in the previous compilation step `optimize-chunks` what suggests that some chunk optimization may be making such change. Follow the [relevant piece of code](https://github.com/rxaviers/globalize-webpack-plugin/blob/de47d5a820b9ba46ea67ddf3de77ac72c292db3e/ProductionModePlugin.js#L119-L144).

A proposed fix is to gather all modules in a step like `optimize-modules`, then on `after-optimize-chunks` use that list.

### PR DESCRIPTION
**Pull request by alunny**
Fixes #21 

Because `module.removeChunk` modifies the underlying array of
module.chunks, using `forEach` (or a for-loop over module.chunks.length)
is not guaranteed to cover all of the chunks in the original array.

This change guarantees that all chunks have the developmentLocale
modules removed, or throws an error.

(also includes some semicolons to please jshint)

Signed-off-by: Andrew Lunny <alunny@twitter.com>

### CODE REVIEW

File: ProductionModePlugin.js [hunk 1]
```diff
@@ -129,8 +129,16 @@ ProductionModePlugin.prototype.apply = function(compiler) {
...
+          while (module.chunks.length) {
+            chunk = module.chunks[0];
+            chunkRemoved = module.removeChunk(chunk);
+            if (!chunkRemoved) {
+              throw new Error("Failed to remove chunk " + chunk.id + " for module " + module.request);
+            }
+          }
           module.chunks.forEach(function(chunk) {
             module.removeChunk(chunk);
           });
```
Comment (rxaviers) [inline ProductionModePlugin.js]: I thought you would replace the `forEach` block with the `while` one. Forgot to remove this? :)

Comment (alunny) [inline ProductionModePlugin.js]: D'oh - that's what I get for staying up late

Comment (rxaviers) [inline ProductionModePlugin.js]: :)

**Comment by rxaviers** [comment]
:+1:

**Comment by alunny** [comment]
I'll merge this in and release a point release.

**Comment by rxaviers** [comment]
Great job.
